#############################################################################
# Makefile for building: ia_busqueda
# Generated by qmake (3.1) (Qt 6.0.0)
# Project:  ../ia_busqueda/ia_busqueda.pro
# Template: app
# Command: C:/Qt/6.0.0/mingw81_64/bin/qmake.exe -o Makefile ../ia_busqueda/ia_busqueda.pro -spec win32-g++ CONFIG+=qtquickcompiler
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = C:/Qt/6.0.0/mingw81_64/bin/qmake.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = cp -f
INSTALL_PROGRAM = cp -f
INSTALL_DIR   = cp -f -R
QINSTALL      = C:/Qt/6.0.0/mingw81_64/bin/qmake.exe -install qinstall
QINSTALL_PROGRAM = C:/Qt/6.0.0/mingw81_64/bin/qmake.exe -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
IDC           = idc
IDL           = midl
ZIP           = 
DEF_FILE      = 
RES_FILE      = 
SED           = sed
MOVE          = mv -f
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: ../ia_busqueda/ia_busqueda.pro C:/Qt/6.0.0/mingw81_64/mkspecs/win32-g++/qmake.conf C:/Qt/6.0.0/mingw81_64/mkspecs/features/spec_pre.prf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/features/device_config.prf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/common/sanitize.conf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/common/gcc-base.conf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/common/g++-base.conf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/features/win32/windows_vulkan_sdk.prf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/common/windows-vulkan.conf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/common/g++-win32.conf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/common/windows-desktop.conf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/qconfig.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_ext_freetype.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_ext_harfbuzz.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_ext_libpng.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_ext_pcre2.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_concurrent.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_core.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_core_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_core_qobject_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_dbus.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_dbus_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_designer.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_designer_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_entrypoint.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_entrypoint_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_fbsupport_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_gui.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_gui_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_help.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_help_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_linguist.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_linguist_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_network.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_network_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_opengl.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_opengl_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_printsupport.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_qml.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_qml_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_quick.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_quick_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_quicktest.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_quicktest_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_sql.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_sql_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_svg.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_svg_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_testlib.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_testlib_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_tools_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_uiplugin.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_uiplugin_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_uitools.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_uitools_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_widgets.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_widgets_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_xml.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_xml_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_zlib_private.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_labsanimationplugin.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_labsmodelsplugin.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_modelsplugin.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_particlesplugin.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qdirect2d.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qgif.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qico.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qjpeg.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qminimal.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmldbg_messages.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmldbg_preview.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmlfolderlistmodelplugin.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmllocalstorageplugin.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmlplugin.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmlsettingsplugin.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmlshapesplugin.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmltestplugin.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmlwavefrontmeshplugin.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qoffscreen.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qquicklayoutsplugin.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qquickwidget.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qsqlite.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qsqlodbc.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qsqlpsql.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qsvg.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qsvgicon.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtlabsplatformplugin.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtquick2plugin.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtquickcontrols2basicstyleimplplugin.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtquickcontrols2basicstyleplugin.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtquickcontrols2fusionstyleimplplugin.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtquickcontrols2fusionstyleplugin.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtquickcontrols2imaginestyleimplplugin.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtquickcontrols2imaginestyleplugin.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtquickcontrols2implplugin.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtquickcontrols2materialstyleimplplugin.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtquickcontrols2materialstyleplugin.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtquickcontrols2nativestyleplugin.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtquickcontrols2plugin.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtquickcontrols2universalstyleimplplugin.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtquickcontrols2universalstyleplugin.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtquickcontrols2windowsstyleplugin.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtquicktemplates2plugin.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qwindows.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qwindowsvistastyle.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_sharedimageplugin.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_workerscriptplugin.pri \
		C:/Qt/6.0.0/mingw81_64/mkspecs/features/qt_functions.prf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/features/qt_config.prf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/win32-g++/qmake.conf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/features/spec_post.prf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/features/exclusive_builds.prf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/features/toolchain.prf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/features/default_pre.prf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/features/win32/default_pre.prf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/features/resolve_config.prf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/features/exclusive_builds_post.prf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/features/default_post.prf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/features/qtquickcompiler.prf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/features/entrypoint.prf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/features/precompile_header.prf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/features/warn_on.prf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/features/qt.prf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/features/resources_functions.prf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/features/resources.prf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/features/moc.prf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/features/win32/opengl.prf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/features/uic.prf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/features/qmake_use.prf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/features/file_copies.prf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/features/win32/windows.prf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/features/testcase_targets.prf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/features/exceptions.prf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/features/yacc.prf \
		C:/Qt/6.0.0/mingw81_64/mkspecs/features/lex.prf \
		../ia_busqueda/ia_busqueda.pro \
		C:/Qt/6.0.0/mingw81_64/lib/Qt6EntryPoint.prl \
		.qmake.stash \
		C:/Qt/6.0.0/mingw81_64/mkspecs/features/build_pass.prf \
		../ia_busqueda/icons.qrc
	$(QMAKE) -o Makefile ../ia_busqueda/ia_busqueda.pro -spec win32-g++ CONFIG+=qtquickcompiler
C:/Qt/6.0.0/mingw81_64/mkspecs/features/spec_pre.prf:
C:/Qt/6.0.0/mingw81_64/mkspecs/features/device_config.prf:
C:/Qt/6.0.0/mingw81_64/mkspecs/common/sanitize.conf:
C:/Qt/6.0.0/mingw81_64/mkspecs/common/gcc-base.conf:
C:/Qt/6.0.0/mingw81_64/mkspecs/common/g++-base.conf:
C:/Qt/6.0.0/mingw81_64/mkspecs/features/win32/windows_vulkan_sdk.prf:
C:/Qt/6.0.0/mingw81_64/mkspecs/common/windows-vulkan.conf:
C:/Qt/6.0.0/mingw81_64/mkspecs/common/g++-win32.conf:
C:/Qt/6.0.0/mingw81_64/mkspecs/common/windows-desktop.conf:
C:/Qt/6.0.0/mingw81_64/mkspecs/qconfig.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_ext_freetype.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_ext_harfbuzz.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_ext_libpng.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_ext_pcre2.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_concurrent.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_concurrent_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_core.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_core_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_core_qobject_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_dbus.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_dbus_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_designer.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_designer_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_entrypoint.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_entrypoint_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_fbsupport_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_gui.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_gui_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_help.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_help_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_linguist.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_linguist_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_network.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_network_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_opengl.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_opengl_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_openglwidgets.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_openglwidgets_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_printsupport.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_printsupport_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_qml.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_qml_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_qmlmodels.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_quick.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_quick_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_quicktest.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_quicktest_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_quickwidgets.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_sql.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_sql_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_svg.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_svg_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_svgwidgets.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_svgwidgets_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_testlib.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_testlib_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_tools_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_uiplugin.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_uiplugin_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_uitools.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_uitools_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_widgets.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_widgets_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_xml.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_xml_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_lib_zlib_private.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_labsanimationplugin.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_labsmodelsplugin.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_modelsplugin.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_particlesplugin.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qdirect2d.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qgif.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qico.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qjpeg.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qminimal.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmldbg_debugger.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmldbg_local.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmldbg_messages.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmldbg_native.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmldbg_preview.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmldbg_profiler.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmldbg_server.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmlfolderlistmodelplugin.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmllocalstorageplugin.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmlplugin.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmlsettingsplugin.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmlshapesplugin.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmltestplugin.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qmlwavefrontmeshplugin.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qoffscreen.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qquicklayoutsplugin.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qquickwidget.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qsqlite.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qsqlodbc.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qsqlpsql.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qsvg.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qsvgicon.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtlabsplatformplugin.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtquick2plugin.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtquickcontrols2basicstyleimplplugin.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtquickcontrols2basicstyleplugin.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtquickcontrols2fusionstyleimplplugin.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtquickcontrols2fusionstyleplugin.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtquickcontrols2imaginestyleimplplugin.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtquickcontrols2imaginestyleplugin.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtquickcontrols2implplugin.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtquickcontrols2materialstyleimplplugin.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtquickcontrols2materialstyleplugin.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtquickcontrols2nativestyleplugin.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtquickcontrols2plugin.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtquickcontrols2universalstyleimplplugin.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtquickcontrols2universalstyleplugin.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtquickcontrols2windowsstyleplugin.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtquicktemplates2plugin.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qwindows.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_qwindowsvistastyle.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_sharedimageplugin.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/modules/qt_plugin_workerscriptplugin.pri:
C:/Qt/6.0.0/mingw81_64/mkspecs/features/qt_functions.prf:
C:/Qt/6.0.0/mingw81_64/mkspecs/features/qt_config.prf:
C:/Qt/6.0.0/mingw81_64/mkspecs/win32-g++/qmake.conf:
C:/Qt/6.0.0/mingw81_64/mkspecs/features/spec_post.prf:
C:/Qt/6.0.0/mingw81_64/mkspecs/features/exclusive_builds.prf:
C:/Qt/6.0.0/mingw81_64/mkspecs/features/toolchain.prf:
C:/Qt/6.0.0/mingw81_64/mkspecs/features/default_pre.prf:
C:/Qt/6.0.0/mingw81_64/mkspecs/features/win32/default_pre.prf:
C:/Qt/6.0.0/mingw81_64/mkspecs/features/resolve_config.prf:
C:/Qt/6.0.0/mingw81_64/mkspecs/features/exclusive_builds_post.prf:
C:/Qt/6.0.0/mingw81_64/mkspecs/features/default_post.prf:
C:/Qt/6.0.0/mingw81_64/mkspecs/features/qtquickcompiler.prf:
C:/Qt/6.0.0/mingw81_64/mkspecs/features/entrypoint.prf:
C:/Qt/6.0.0/mingw81_64/mkspecs/features/precompile_header.prf:
C:/Qt/6.0.0/mingw81_64/mkspecs/features/warn_on.prf:
C:/Qt/6.0.0/mingw81_64/mkspecs/features/qt.prf:
C:/Qt/6.0.0/mingw81_64/mkspecs/features/resources_functions.prf:
C:/Qt/6.0.0/mingw81_64/mkspecs/features/resources.prf:
C:/Qt/6.0.0/mingw81_64/mkspecs/features/moc.prf:
C:/Qt/6.0.0/mingw81_64/mkspecs/features/win32/opengl.prf:
C:/Qt/6.0.0/mingw81_64/mkspecs/features/uic.prf:
C:/Qt/6.0.0/mingw81_64/mkspecs/features/qmake_use.prf:
C:/Qt/6.0.0/mingw81_64/mkspecs/features/file_copies.prf:
C:/Qt/6.0.0/mingw81_64/mkspecs/features/win32/windows.prf:
C:/Qt/6.0.0/mingw81_64/mkspecs/features/testcase_targets.prf:
C:/Qt/6.0.0/mingw81_64/mkspecs/features/exceptions.prf:
C:/Qt/6.0.0/mingw81_64/mkspecs/features/yacc.prf:
C:/Qt/6.0.0/mingw81_64/mkspecs/features/lex.prf:
../ia_busqueda/ia_busqueda.pro:
C:/Qt/6.0.0/mingw81_64/lib/Qt6EntryPoint.prl:
.qmake.stash:
C:/Qt/6.0.0/mingw81_64/mkspecs/features/build_pass.prf:
../ia_busqueda/icons.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile ../ia_busqueda/ia_busqueda.pro -spec win32-g++ CONFIG+=qtquickcompiler

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
